pipeline:
    name: Remote with Triggers and Input Sets
    identifier: Remote_with_Triggers_and_Input_Sets
    projectIdentifier: kapil_digani_project
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Approval
              identifier: Approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: echo
                                identifier: echo
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: <+input>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                name: Approvers
                                identifier: Approvers
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups: <+input>
                                    approverInputs: []
              tags: {}
    description: Test
