pipeline:
    name: Random
    identifier: Random
    projectIdentifier: kapil_digani_test
    orgIdentifier: aaaorg
    storeType: REMOTE
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: Approval
              identifier: Approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approvers
                                identifier: Approvers
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.Approvers
                                    approverInputs: []
              tags: {}
